name: CI

on: [push]

jobs:
  composer-normalize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Composer normalize
        uses: localheinz/composer-normalize-action@0.5.2
